### ISSUE TITLE
Post images as links

### ISSUE THREAD

**Issue by Ruriko** [jwansek/RSSPoster#1]
Is it possible to make it post images from RSS as the link for reddit? like for example I use this RSS http://pix.adoreanime.com:1200/pixiv/search/vocaloid/other/safe but I want to use the image url instead of the post url

**Comment by jwansek** [comment]
This is absolutely possible, but I think out of scope for this project since each site will have images in a different part of their RSS feed and I don't think there's a way of making this work universally. Sorry!
